apiVersion: batch/v1
kind: Job
metadata:
  generateName: premium-job-
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: premium-container
        image: twig818/classifier-image:latest
        env:
        - name: DATASET
          value: "kmnist"
        - name: TYPE
          value: "cnn"
        resources:
          requests:
            cpu: "0.9"
          limits:
            cpu: "0.9"
      restartPolicy: Never


